---
- hosts: demo
  become: true
  become_method: sudo

  vars:
    users:
      - name: vasim
        group: vasim
        password: vasim1
      # - name: diwan
      #   group: diwan
      #   password: diwan1
      # - name: pravin
      #   group: pravin
      #   password: pravin1

  tasks:
    # - name: Adding users
    users:
      name: "{{item}}"
      shell: /bin/bash
      append: yes
      state: present
    # with_items: "{{users}}"
