---
- hosts: demo
  become: true
  become_method: sudo

  # vars:
    # users:
  tasks:
      - name: vasim
        group: vasim
        password: vasim1
        state: present
        
      # - name: diwan
      #   group: diwan
      #   password: diwan1
      # - name: pravin
      #   group: pravin
      #   password: pravin1

  # tasks:
  #   - name: Adding users
  #     user:
  #       name: "{{item}}"
  #       shell: /bin/bash
  #       append: yes
  #       state: present
  #     with_items: "{{vasim, }}"
