- hosts: all
  gather_facts: true
  become: true
  #become_method: sudo
  vars:
    files:
      - /home/semaphore/.ssh
    #  - /home/mobme-reports/.ssh
     # - /etc/default/iptables
     # - /etc/cron.d
    #  - /etc/network/interfaces 
  tasks:
    - name: Backup running on {{ansible_hostname}} server
      synchronize:
        src: '{{item}}'
        dest: /home/semaphore/backups/{{ansible_hostname}}
        mode: pull
      with_items: "{{files}}"
