---
- name: Install and Start the service
  hosts: demo
  become: true


  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: present
    - name: Starting the nginx service
      service:
          name: httpd
          state: started
          enabled: true
