- hosts: demo
  gather_facts: true
  connection: ssh
  become: true
  #become_method: sudo

  tasks:

  - name: Install the package "httpd"
    yum:
      name: httpd -y
      state: present
      update_cache: yes
