- hosts: all
  gather_facts: true
  connection: ssh
  become: true
  #become_method: sudo

  tasks:

  - name: Install the package "nagios-plugins"
    yum:
      name: nagios-plugins
      state: present
      update_cache: yes
